/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AnalystRole;

import Business.EcoSystem;
import Business.Enterprise.AnalyticsDepartment.AnalystHelper;
import Business.Enterprise.AnalyticsDepartment.Report;
import Business.Enterprise.CoffeeChainEnterprise;
import Business.Enterprise.DeliveryDepartment.DeliveryDirectory;
import Business.Enterprise.DeliveryEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AnalystOrganization;
import Business.Organization.CafeOperationOrganization;
import Business.Organization.DeliveryDispatcherOrganization;
import Business.Organization.Organization;
import Business.OrderQueue.CoffeeOrderRequest;
import Business.OrderQueue.OrderQueue;
import Business.OrderQueue.OrderRequest;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Luciela us Biktria
 */
public class AnalystWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final AnalystOrganization organization;
    private final EcoSystem system;
    
    // We need temporary references to the data we are analyzing
    private DeliveryDirectory targetDeliveryDirectory;
    private OrderQueue aggregatedOrderQueue;

    /**
     * Creates new form AnalystWorkAreaJPanel
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param business
     */
    public AnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (AnalystOrganization) organization;
        this.system = business;
        
        txtReportArea.setEditable(false);
        
        populateOldReportsList();
    }
    
    /**
     * Traverses the EcoSystem to find the Delivery Data and all Coffee Orders.
     * This ensures the Analyst sees the most up-to-date data when generating a report.
     */
    private void refreshDataSources() {
        aggregatedOrderQueue = new OrderQueue();
        targetDeliveryDirectory = null;
        
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                
                if (e instanceof DeliveryEnterprise) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof DeliveryDispatcherOrganization deliveryDispatcherOrganization) {
                            this.targetDeliveryDirectory = deliveryDispatcherOrganization.getDeliveryDirectory();
                        }
                    }
                }
                
                if (e instanceof CoffeeChainEnterprise) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof CafeOperationOrganization) {
                            for (OrderRequest req : org.getWorkQueue().getWorkRequestList()) {
                                if (req instanceof CoffeeOrderRequest) {
                                    aggregatedOrderQueue.getWorkRequestList().add(req);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    private void populateOldReportsList() {
        DefaultListModel<Object> model = new DefaultListModel<>();
        for (Report r : organization.getReportDirectory().getReports()) {
            model.addElement(r); // Report.toString() returns the timestamp
        }
        lstOldReports.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReportArea = new javax.swing.JTextArea();
        btnGenReport = new javax.swing.JButton();
        chkFastRiders = new javax.swing.JCheckBox();
        chkSlowRiders = new javax.swing.JCheckBox();
        chkRiderActivity = new javax.swing.JCheckBox();
        chkTopDestination = new javax.swing.JCheckBox();
        chkRegionActivity = new javax.swing.JCheckBox();
        chkOrderRegions = new javax.swing.JCheckBox();
        chkDeliveryPercent = new javax.swing.JCheckBox();
        btnGetRepot = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOldReports = new javax.swing.JList<>();
        lblNewReport = new javax.swing.JLabel();
        lblPreviousReports = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Delivery and Order Metrics");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        txtReportArea.setColumns(20);
        txtReportArea.setRows(5);
        jScrollPane1.setViewportView(txtReportArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 85, 350, 450));

        btnGenReport.setText("Generate Report");
        btnGenReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenReportActionPerformed(evt);
            }
        });
        add(btnGenReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        chkFastRiders.setText("Fastest Riders");
        add(chkFastRiders, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        chkSlowRiders.setText("Slowest Riders");
        add(chkSlowRiders, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        chkRiderActivity.setText("Rider Activity");
        add(chkRiderActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        chkTopDestination.setText("Top Destinations");
        add(chkTopDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        chkRegionActivity.setText("Region Activity");
        add(chkRegionActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        chkOrderRegions.setText("Popular Orders");
        add(chkOrderRegions, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        chkDeliveryPercent.setText("Delivery vs. Dine-In");
        add(chkDeliveryPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        btnGetRepot.setText("Fetch Report");
        btnGetRepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRepotActionPerformed(evt);
            }
        });
        add(btnGetRepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 130, -1));

        jScrollPane2.setViewportView(lstOldReports);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 110, 200));

        lblNewReport.setText("New Report");
        add(lblNewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblPreviousReports.setText("Previous Reports");
        add(lblPreviousReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenReportActionPerformed
        refreshDataSources();
        
        if (targetDeliveryDirectory == null) {
            JOptionPane.showMessageDialog(this, "No Delivery Organization found in system to analyze.");
            return;
        }
        
        StringBuilder sb = new StringBuilder();
        sb.append("ANALYTICS REPORT\n");
        sb.append("Generated on: ").append(new Date().toString()).append("\n");
        sb.append("========================================\n\n");
        
        boolean anythingSelected = false;
        
        // Append selected sections using AnalystHelper
        
        if (chkFastRiders.isSelected()) {
            sb.append(AnalystHelper.getTop5FastestRiders(targetDeliveryDirectory));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (chkSlowRiders.isSelected()) {
            sb.append(AnalystHelper.getTop5SlowestRiders(targetDeliveryDirectory));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (chkRiderActivity.isSelected()) {
            sb.append(AnalystHelper.getRiderActivityStats(targetDeliveryDirectory));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (chkTopDestination.isSelected()) {
            sb.append(AnalystHelper.getTop3Destinations(targetDeliveryDirectory));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (chkRegionActivity.isSelected()) {
            sb.append(AnalystHelper.getRegionStats(targetDeliveryDirectory));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (chkOrderRegions.isSelected()) {
            sb.append(AnalystHelper.getPopularOrdersAnalysis(aggregatedOrderQueue));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (chkDeliveryPercent.isSelected()) {
            sb.append(AnalystHelper.getDeliveryPercentage(aggregatedOrderQueue));
            sb.append("\n----------------------------------------\n\n");
            anythingSelected = true;
        }
        
        if (!anythingSelected) {
            JOptionPane.showMessageDialog(this, "Please select at least one metric to generate a report.");
            return;
        }
        
        String finalReport = sb.toString();
        Report reportObj = new Report(finalReport);
        organization.getReportDirectory().addReport(reportObj);
        txtReportArea.setText(finalReport);
        populateOldReportsList(); // Refresh list to show new report
        
    }//GEN-LAST:event_btnGenReportActionPerformed

    private void btnGetRepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRepotActionPerformed
        Object selected = lstOldReports.getSelectedValue();
        
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a report from the list.");
            return;
        }
        
        if (selected instanceof Report r) {
            txtReportArea.setText(r.getContent());
        }
    }//GEN-LAST:event_btnGetRepotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenReport;
    private javax.swing.JButton btnGetRepot;
    private javax.swing.JCheckBox chkDeliveryPercent;
    private javax.swing.JCheckBox chkFastRiders;
    private javax.swing.JCheckBox chkOrderRegions;
    private javax.swing.JCheckBox chkRegionActivity;
    private javax.swing.JCheckBox chkRiderActivity;
    private javax.swing.JCheckBox chkSlowRiders;
    private javax.swing.JCheckBox chkTopDestination;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNewReport;
    private javax.swing.JLabel lblPreviousReports;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<Object> lstOldReports;
    private javax.swing.JTextArea txtReportArea;
    // End of variables declaration//GEN-END:variables
}