/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.FrontDeskRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.OrderQueue.CoffeeOrderRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class OrderRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     * @param userProcessContainer
     * @param account
     * @param enterprise
     */
    public OrderRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        deliveryAddressText.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placeOrderJButton = new javax.swing.JButton();
        CoffeeLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        cmbOrder = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        cmbOrder1 = new javax.swing.JComboBox<>();
        typeLabel1 = new javax.swing.JLabel();
        deliveryAddressText = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placeOrderJButton.setText("Place Order");
        placeOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderJButtonActionPerformed(evt);
            }
        });
        add(placeOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        CoffeeLabel.setText("Coffee:");
        add(CoffeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 40));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, 20));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 40));

        cmbOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Americano", "Latte", "Mocha", "Espresso" }));
        cmbOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrderActionPerformed(evt);
            }
        });
        add(cmbOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        typeLabel.setText("Type:");
        add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 40));

        cmbOrder1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine-in", "Delivery" }));
        cmbOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrder1ActionPerformed(evt);
            }
        });
        add(cmbOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        typeLabel1.setText("Delivery Address:");
        add(typeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 40));

        deliveryAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryAddressTextActionPerformed(evt);
            }
        });
        add(deliveryAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderJButtonActionPerformed
        
String coffeeType = cmbOrder.getSelectedItem().toString();
        String type = cmbOrder1.getSelectedItem().toString();
        
   
        String address = "";
        if ("Delivery".equals(type)) {
            address = deliveryAddressText.getText();
            if (address.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a delivery address!");
                return; 
            }
        }
        
        CoffeeOrderRequest request = new CoffeeOrderRequest();
        request.setMessage(coffeeType);
        request.setOrderType(type);
        

        if ("Delivery".equals(type)) {
            request.setDestination(1, address); 
        } else {

            request.setDestination(); 
        }

        request.setSender(userAccount);
        request.setStatus("Sent");
        

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){

            if (organization instanceof Business.Organization.BeverageProductionOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            
            JOptionPane.showMessageDialog(null, "Order Placed Successfully!");
            

            deliveryAddressText.setText("");
        } else {
             JOptionPane.showMessageDialog(null, "system error");
        
        }
        
    }//GEN-LAST:event_placeOrderJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FrontDeskWorkAreaJPanel dwjp = (FrontDeskWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrderActionPerformed

    private void cmbOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrder1ActionPerformed
        // TODO add your handling code here:
        String selectedType = cmbOrder1.getSelectedItem().toString();
        
        if ("Delivery".equals(selectedType)) {
            deliveryAddressText.setEnabled(true);
        } else {
            deliveryAddressText.setEnabled(false);
            deliveryAddressText.setText("");
        }
        
    }//GEN-LAST:event_cmbOrder1ActionPerformed

    private void deliveryAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryAddressTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoffeeLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> cmbOrder;
    private javax.swing.JComboBox<String> cmbOrder1;
    private javax.swing.JTextField deliveryAddressText;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton placeOrderJButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeLabel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
