/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.StoreManagerRole;

import Business.EcoSystem;
import Business.Organization.CafeManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.OrderQueue.OrderRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FoodSupplyEnterprise;
import Business.Network.Network;
import Business.Organization.WarehouseOrganization;
import Business.OrderQueue.SupplyOrderRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author raunak
 */
public class StoreManagerWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final EcoSystem business;
    private final UserAccount userAccount;
    private final CafeManagementOrganization labOrganization;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     * @param userProcessContainer
     * @param business
     * @param organization
     * @param account
     */
    public StoreManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.labOrganization = (CafeManagementOrganization)organization;
        
        populateSupplyOrdersTable();
    }
    
    private WarehouseOrganization findWarehouseOrganization() {
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof FoodSupplyEnterprise) {
                    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof WarehouseOrganization) {
                            return (WarehouseOrganization) org;
                        }
                    }
                }
            }
        }
        return null;
    }
    

    
    private void populateSupplyOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) tblSupplyOrders.getModel();
        model.setRowCount(0);

        // Show all SupplyOrderRequests where this user is the sender
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (OrderRequest req : org.getWorkQueue().getWorkRequestList()) {
                        if (req instanceof SupplyOrderRequest) {
                            SupplyOrderRequest sReq = (SupplyOrderRequest) req;

                            // Only show requests created by this Store Manager
                            if (sReq.getSender() == userAccount) {
                                Object[] row = new Object[5];
                                row[0] = sReq.getItemName();
                                row[1] = sReq.getQuantity();
                                row[2] = sReq.getStatus();
                                row[3] = sReq.getSender() == null ? "" : sReq.getSender().getUsername();
                                row[4] = sReq.getReceiver() == null ? "" : sReq.getReceiver().getUsername();

                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblItem1 = new javax.swing.JLabel();
        btnRequestSupplies = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplyOrders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbSupplyItem = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuantity.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblQuantity.setText("Quantity");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 70, -1));
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 150, -1));

        lblItem1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblItem1.setText("Item");
        add(lblItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 40, -1));

        btnRequestSupplies.setText("Request Supplies");
        btnRequestSupplies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestSuppliesActionPerformed(evt);
            }
        });
        add(btnRequestSupplies, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 210, -1));

        tblSupplyOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Status", "Sender", "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSupplyOrders);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 900, 140));

        jLabel1.setText("Supply Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        cmbSupplyItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coffee - Dark Roast", "Coffee - Medium Roast", "Coffee - Light Roast", "Coffee - Espresso", "Coffee - Decaf", "Cups - Small (12oz)", "Cups - Medium (16oz)", "Cups - Large (20oz)", "Milk - Whole", "Milk - Skim", "Milk - Almond", "Milk - Oat", "Other" }));
        add(cmbSupplyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestSuppliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestSuppliesActionPerformed
        // TODO add your handling code here:
        
        Object selected = cmbSupplyItem.getSelectedItem();
        String qtyText = txtQuantity.getText().trim();

        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a supply item.");
            return;
        }

        if (qtyText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity.");
            return;
        }

        String itemName = selected.toString();

        int quantity;
        try {
            quantity = Integer.parseInt(qtyText);
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be a positive number.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a number.");
            return;
        }

        WarehouseOrganization warehouseOrg = findWarehouseOrganization();
        if (warehouseOrg == null) {
            JOptionPane.showMessageDialog(this, "No Warehouse organization found in FoodSupply enterprise.");
            return;
        }

        SupplyOrderRequest request = new SupplyOrderRequest();
        request.setStoreName(labOrganization.getName());
        request.setItemName(itemName);   
        request.setQuantity(quantity);
        request.setSender(userAccount);
        request.setStatus("Sent to Warehouse");

        warehouseOrg.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(this, "Supply request sent to Warehouse.");

        // reset inputs
        cmbSupplyItem.setSelectedIndex(0);
        txtQuantity.setText("");
        
        populateSupplyOrdersTable();
    }//GEN-LAST:event_btnRequestSuppliesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestSupplies;
    private javax.swing.JComboBox<String> cmbSupplyItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTable tblSupplyOrders;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
        
        
}
