/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RiderRole;

import Business.Enterprise.DeliveryDepartment.Rider;
import Business.Organization.DeliveryDispatcherOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Luciela us Biktria
 */
public class ManageAccountJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final DeliveryDispatcherOrganization organization;
    private Rider currentRider;
    
    private final JCheckBox[] regionCheckBoxes;
    private boolean editMode = false;

    /**
     * Creates new form ManageAccountJPanel
     * @param userProcessContainer
     * @param userAccount
     * @param organization
     */
    public ManageAccountJPanel(JPanel userProcessContainer, UserAccount userAccount, DeliveryDispatcherOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        
        regionCheckBoxes = new JCheckBox[] {
            chkRiderRegion1, chkRiderRegion2, chkRiderRegion3, chkRiderRegion4, 
            chkRiderRegion5, chkRiderRegion6, chkRiderRegion7, chkRiderRegion8, 
            chkRiderRegion9, chkRiderRegion10
        };
        
        identifyRider();
        populateFields();
    }
    
    private void identifyRider() {
        // Find the Rider object in the directory that matches the logged-in Employee name
        String empName = userAccount.getEmployee().getName();
        for (Rider r : organization.getRiderDirectory().getEmployeeList()) {
            String riderName = r.getFirstName() + " " + r.getLastName();
            if (riderName.equals(empName)) {
                currentRider = r;
                break;
            }
        }
        
        if (currentRider == null) {
            JOptionPane.showMessageDialog(this, "Error: Could not find associated Rider profile for this account.");
            btnSaveEdit.setEnabled(false);
        }
    }
    
    private void populateFields() {
        if (currentRider == null) return;
        
        txtRiderID.setText(String.valueOf(currentRider.getId()));
        txtRiderPhoneNum.setText(String.valueOf(currentRider.getPhoneNumber()));
        txtRiderFirstName.setText(currentRider.getFirstName());
        txtRiderLastName.setText(currentRider.getLastName());
        
        txtAccountUsername.setText(userAccount.getUsername());
        txtAccountPassword.setText(userAccount.getPassword());
        
        // Regions
        for (JCheckBox chk : regionCheckBoxes) {
            chk.setSelected(false);
        }
        if (currentRider.getRegions() != null) {
            for (int r : currentRider.getRegions()) {
                if (r >= 1 && r <= 10) {
                    regionCheckBoxes[r-1].setSelected(true);
                }
            }
        }
    }
    
    private void setEditable(boolean editable) {
        // ID and Username are read-only for self-service
        // txtRiderID.setEnabled(editable); 
        // txtAccountUsername.setEnabled(editable); 
        
        txtRiderPhoneNum.setEnabled(editable);
        txtRiderFirstName.setEnabled(editable);
        txtRiderLastName.setEnabled(editable);
        txtAccountPassword.setEnabled(editable);
        
        for (JCheckBox chk : regionCheckBoxes) {
            chk.setEnabled(editable);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblRiderID = new javax.swing.JLabel();
        lblRiderPhoneNum = new javax.swing.JLabel();
        lblRiderFirstName = new javax.swing.JLabel();
        lblRiderLastName = new javax.swing.JLabel();
        lblAccountUsername = new javax.swing.JLabel();
        lblAccountPassword = new javax.swing.JLabel();
        lblRiderRegions = new javax.swing.JLabel();
        chkRiderRegion1 = new javax.swing.JCheckBox();
        chkRiderRegion2 = new javax.swing.JCheckBox();
        chkRiderRegion3 = new javax.swing.JCheckBox();
        chkRiderRegion4 = new javax.swing.JCheckBox();
        chkRiderRegion5 = new javax.swing.JCheckBox();
        chkRiderRegion6 = new javax.swing.JCheckBox();
        chkRiderRegion7 = new javax.swing.JCheckBox();
        chkRiderRegion8 = new javax.swing.JCheckBox();
        chkRiderRegion9 = new javax.swing.JCheckBox();
        chkRiderRegion10 = new javax.swing.JCheckBox();
        txtRiderID = new javax.swing.JTextField();
        txtRiderPhoneNum = new javax.swing.JTextField();
        txtRiderFirstName = new javax.swing.JTextField();
        txtRiderLastName = new javax.swing.JTextField();
        txtAccountUsername = new javax.swing.JTextField();
        txtAccountPassword = new javax.swing.JPasswordField();
        btnSaveEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Rider Account Management");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        lblRiderID.setText("Rider ID");
        add(lblRiderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        lblRiderPhoneNum.setText("Rider Phone Number");
        add(lblRiderPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblRiderFirstName.setText("Rider First Name");
        add(lblRiderFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        lblRiderLastName.setText("Rider Last Name");
        add(lblRiderLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        lblAccountUsername.setText("Account Username");
        add(lblAccountUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        lblAccountPassword.setText("Account Password");
        add(lblAccountPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        lblRiderRegions.setText("Rider Delivery Regions");
        add(lblRiderRegions, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        chkRiderRegion1.setText("Region 1");
        chkRiderRegion1.setEnabled(false);
        add(chkRiderRegion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        chkRiderRegion2.setText("Region 2");
        chkRiderRegion2.setEnabled(false);
        add(chkRiderRegion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        chkRiderRegion3.setText("Region 3");
        chkRiderRegion3.setEnabled(false);
        add(chkRiderRegion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        chkRiderRegion4.setText("Region 4");
        chkRiderRegion4.setEnabled(false);
        add(chkRiderRegion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        chkRiderRegion5.setText("Region 5");
        chkRiderRegion5.setEnabled(false);
        add(chkRiderRegion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        chkRiderRegion6.setText("Region 6");
        chkRiderRegion6.setEnabled(false);
        add(chkRiderRegion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        chkRiderRegion7.setText("Region 7");
        chkRiderRegion7.setEnabled(false);
        add(chkRiderRegion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        chkRiderRegion8.setText("Region 8");
        chkRiderRegion8.setEnabled(false);
        add(chkRiderRegion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        chkRiderRegion9.setText("Region 9");
        chkRiderRegion9.setEnabled(false);
        add(chkRiderRegion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        chkRiderRegion10.setText("Region 10");
        chkRiderRegion10.setEnabled(false);
        add(chkRiderRegion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        txtRiderID.setEnabled(false);
        txtRiderID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRiderIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRiderIDFocusLost(evt);
            }
        });
        add(txtRiderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, -1));

        txtRiderPhoneNum.setEnabled(false);
        txtRiderPhoneNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRiderPhoneNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRiderPhoneNumFocusLost(evt);
            }
        });
        add(txtRiderPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 230, -1));

        txtRiderFirstName.setEnabled(false);
        add(txtRiderFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 230, -1));

        txtRiderLastName.setEnabled(false);
        add(txtRiderLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 230, -1));

        txtAccountUsername.setEnabled(false);
        add(txtAccountUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 230, -1));

        txtAccountPassword.setText("jPasswordField1");
        txtAccountPassword.setEnabled(false);
        add(txtAccountPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 230, -1));

        btnSaveEdit.setText("Edit");
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });
        add(btnSaveEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 110, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 140, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRiderIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRiderIDFocusGained
    }//GEN-LAST:event_txtRiderIDFocusGained

    private void txtRiderIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRiderIDFocusLost
    }//GEN-LAST:event_txtRiderIDFocusLost

    private void txtRiderPhoneNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRiderPhoneNumFocusGained
    }//GEN-LAST:event_txtRiderPhoneNumFocusGained

    private void txtRiderPhoneNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRiderPhoneNumFocusLost
    }//GEN-LAST:event_txtRiderPhoneNumFocusLost

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (editMode) {
            editMode = false;
            setEditable(false);
            btnSaveEdit.setText("Edit");
            populateFields(); // Revert changes
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
        if (!editMode) {
            // -- Switch to Edit Mode --
            editMode = true;
            setEditable(true);
            btnSaveEdit.setText("Save");
        } else {
            // -- Save Action --
            String fName = txtRiderFirstName.getText();
            String lName = txtRiderLastName.getText();
            String phoneTxt = txtRiderPhoneNum.getText();
            String password = String.valueOf(txtAccountPassword.getPassword());
            
            if (fName.isBlank() || lName.isBlank() || phoneTxt.isBlank() || password.isBlank()) {
                JOptionPane.showMessageDialog(this, "All fields (Name, Phone, Password) are required.");
                return;
            }
            
            long phone;
            try {
                phone = Long.parseLong(phoneTxt);
                if (String.valueOf(phone).length() != 10) {
                    JOptionPane.showMessageDialog(this, "Phone number must be 10 digits.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Phone number must be numerical.");
                return;
            }
            
            ArrayList<Integer> selectedRegions = new ArrayList<>();
            for(int i=0; i<regionCheckBoxes.length; i++) {
                if(regionCheckBoxes[i].isSelected()) {
                    selectedRegions.add(i+1);
                }
            }
            if (selectedRegions.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select at least one region.");
                return;
            }
            int[] regionsArr = selectedRegions.stream().mapToInt(i->i).toArray();
            
            // Update Data
            currentRider.setFirstName(fName);
            currentRider.setLastName(lName);
            currentRider.setPhoneNumber(phone);
            currentRider.setRegions(regionsArr);
            
            // Sync with UserAccount
            userAccount.setPassword(password);
            userAccount.getEmployee().setName(fName + " " + lName);
            
            JOptionPane.showMessageDialog(this, "Account details updated successfully.");
            
            editMode = false;
            setEditable(false);
            btnSaveEdit.setText("Edit");
            populateFields();
        }
    }//GEN-LAST:event_btnSaveEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JCheckBox chkRiderRegion1;
    private javax.swing.JCheckBox chkRiderRegion10;
    private javax.swing.JCheckBox chkRiderRegion2;
    private javax.swing.JCheckBox chkRiderRegion3;
    private javax.swing.JCheckBox chkRiderRegion4;
    private javax.swing.JCheckBox chkRiderRegion5;
    private javax.swing.JCheckBox chkRiderRegion6;
    private javax.swing.JCheckBox chkRiderRegion7;
    private javax.swing.JCheckBox chkRiderRegion8;
    private javax.swing.JCheckBox chkRiderRegion9;
    private javax.swing.JLabel lblAccountPassword;
    private javax.swing.JLabel lblAccountUsername;
    private javax.swing.JLabel lblRiderFirstName;
    private javax.swing.JLabel lblRiderID;
    private javax.swing.JLabel lblRiderLastName;
    private javax.swing.JLabel lblRiderPhoneNum;
    private javax.swing.JLabel lblRiderRegions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField txtAccountPassword;
    private javax.swing.JTextField txtAccountUsername;
    private javax.swing.JTextField txtRiderFirstName;
    private javax.swing.JTextField txtRiderID;
    private javax.swing.JTextField txtRiderLastName;
    private javax.swing.JTextField txtRiderPhoneNum;
    // End of variables declaration//GEN-END:variables
}