/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RiderRole;

import Business.Enterprise.DeliveryDepartment.Delivery;
import Business.Enterprise.DeliveryDepartment.Rider;
import Business.Organization.DeliveryDispatcherOrganization;
import Business.OrderQueue.CoffeeOrderRequest;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciela us Biktria
 */
public class ReportDeliveryJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final DeliveryDispatcherOrganization organization;
    private Rider currentRider;

    /**
     * Creates new form ReportDeliveryJPanel
     * @param userProcessContainer
     * @param organization
     * @param userAccount
     */
    public ReportDeliveryJPanel(JPanel userProcessContainer, UserAccount userAccount, DeliveryDispatcherOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        
        identifyRider();
        populateTable();
    }
    
    private void identifyRider() {
        String empName = userAccount.getEmployee().getName();
        for (Rider r : organization.getRiderDirectory().getEmployeeList()) {
            String riderName = r.getFirstName() + " " + r.getLastName();
            if (riderName.equals(empName)) {
                currentRider = r;
                break;
            }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrderList.getModel();
        model.setRowCount(0);
        
        if (currentRider == null) return;
        
        for (Delivery d : organization.getDeliveryDirectory().getDeliveryList()) {
            if (d.getRider().equals(currentRider)) {
                CoffeeOrderRequest order = d.getOrder();
                Object[] row = new Object[4];
                row[0] = order;
                row[1] = order.getMessage();
                row[2] = order.getStatus();
                row[3] = (order.getDestination() != null) ? order.getDestination().getAddress() : "N/A";
                
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Report Deliveries");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Order Contents", "Order Status", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 320));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 130, -1));

        btnAccept.setText("Accept Delivery Job");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 150, -1));

        btnReport.setText("Report Delivery");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 480, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        int selectedRow = tblOrderList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order to accept.");
            return;
        }
        
        CoffeeOrderRequest order = (CoffeeOrderRequest) tblOrderList.getValueAt(selectedRow, 0);
        String status = order.getStatus();
        
        if ("In-Progress".equalsIgnoreCase(status) || "Delivered".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "This order has already been accepted or delivered.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Accept this delivery job?", "Confirm Acceptance", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            order.setStatus("In-Progress");
            
            Delivery d = organization.getDeliveryDirectory().findDeliveryByOrder(order);
            if (d != null) {
                d.setDateTimeSent(System.currentTimeMillis()); 
            }
            
            populateTable();
            JOptionPane.showMessageDialog(this, "Order accepted. Status set to In-Progress.");
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        int selectedRow = tblOrderList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order to report.");
            return;
        }
        
        CoffeeOrderRequest order = (CoffeeOrderRequest) tblOrderList.getValueAt(selectedRow, 0);
        String status = order.getStatus();
        
        if (!"In-Progress".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "You must Accept the order before reporting it as delivered.");
            return;
        }
        
        // Confirmation 1
        int confirm1 = JOptionPane.showConfirmDialog(this, "Have you arrived at the destination and delivered the items?", "Confirm Delivery - Step 1", JOptionPane.YES_NO_OPTION);
        if (confirm1 == JOptionPane.YES_OPTION) {
            
            // Confirmation 2
            int confirm2 = JOptionPane.showConfirmDialog(this, "Are you sure you want to mark this as Complete? This cannot be undone.", "Final Confirmation - Step 2", JOptionPane.YES_NO_OPTION);
            
            if (confirm2 == JOptionPane.YES_OPTION) {
                order.setStatus("Delivered");
                
                // Update Delivery Time
                Delivery d = organization.getDeliveryDirectory().findDeliveryByOrder(order);
                if (d != null) {
                    d.setDateTimeArrived(System.currentTimeMillis());
                }
                
                populateTable();
                JOptionPane.showMessageDialog(this, "Delivery reported successfully!");
            }
        }
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrderList;
    // End of variables declaration//GEN-END:variables
}