/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RiderRole;

import Business.Organization.DeliveryDispatcherOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Luciela us Biktria
 */
public class RiderWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DeliveryDispatcherOrganization organization;

    /**
     * Creates new form RiderWorkAreaJPanel
     */
    public RiderWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DeliveryDispatcherOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        
        lblTitle.setText("Welcome, " + userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageAccount = new javax.swing.JButton();
        btnReportDelivery = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Rider Control Panel");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        btnManageAccount.setText("Manage Account");
        btnManageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccountActionPerformed(evt);
            }
        });
        add(btnManageAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 230, -1));

        btnReportDelivery.setText("Accept and Report Deliveries");
        btnReportDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDeliveryActionPerformed(evt);
            }
        });
        add(btnReportDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccountActionPerformed
        ManageAccountJPanel panel = new ManageAccountJPanel(userProcessContainer, userAccount, organization);
        userProcessContainer.add("ManageAccountJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAccountActionPerformed

    private void btnReportDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDeliveryActionPerformed
        ReportDeliveryJPanel panel = new ReportDeliveryJPanel(userProcessContainer, userAccount, organization);
        userProcessContainer.add("ReportDeliveryJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportDeliveryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAccount;
    private javax.swing.JButton btnReportDelivery;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}