/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.BaristaRole;

import Business.EcoSystem;
import Business.Organization.CafeOperationOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.OrderQueue.CoffeeOrderRequest;
import Business.OrderQueue.OrderRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class BaristaWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private CafeOperationOrganization cafeOpOrganization;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public BaristaWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.cafeOpOrganization = (CafeOperationOrganization)organization;
        
        populateTable(); 
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        model.setRowCount(0);
        
        java.util.List<OrderRequest> list = cafeOpOrganization.getWorkQueue().getWorkRequestList();
        
        for (int i = list.size() - 1; i >= 0; i--) {
            OrderRequest request = list.get(i);
            
            CoffeeOrderRequest coffeeReq = (CoffeeOrderRequest) request;
            
            Object[] row = new Object[5];
            row[0] = coffeeReq.getOrderType();
            row[1] = coffeeReq;
            row[2] = coffeeReq.getMessage();
            row[3] = request.getReceiver() == null ? "Waiting" : request.getReceiver();
            row[4] = request.getStatus();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        orderFinishedJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Order#", "Order", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 850, 150));

        assignJButton.setText("Assign Order to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        orderFinishedJButton.setText("Order Finished");
        orderFinishedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderFinishedJButtonActionPerformed(evt);
            }
        });
        add(orderFinishedJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 30, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an order to assign.");
            return;
        }
        
        OrderRequest request = (OrderRequest)workRequestJTable.getValueAt(selectedRow, 1);
        
        if(!"Sent".equals(request.getStatus())){
             JOptionPane.showMessageDialog(null, "This order is already taken or completed.");
             return;
        }
        
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateTable();
        JOptionPane.showMessageDialog(null, "Order assigned to you!");
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void orderFinishedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderFinishedJButtonActionPerformed
        
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an order to finish.");
            return;
        }
        
        CoffeeOrderRequest request = (CoffeeOrderRequest)workRequestJTable.getValueAt(selectedRow, 1);
     
        if(!"Pending".equals(request.getStatus()) || request.getReceiver() != userAccount){
                     JOptionPane.showMessageDialog(null, "You can only finish orders assigned to you and in progress.");
                     return;
                }
        
        request.setStatus("Completed");
        
        populateTable();
        JOptionPane.showMessageDialog(null, "Order Completed!");
        
        
    }//GEN-LAST:event_orderFinishedJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderFinishedJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
