/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeliveryRole;

import Business.EcoSystem;
import Business.Enterprise.CoffeeChainEnterprise;
import Business.Enterprise.DeliveryDepartment.Delivery;
import Business.Enterprise.DeliveryDepartment.DeliveryDirectory;
import Business.Enterprise.DeliveryDepartment.Rider;
import Business.Enterprise.DeliveryDepartment.RiderDirectory;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CafeOperationOrganization;
import Business.Organization.Organization;
import Business.OrderQueue.CoffeeOrderRequest;
import Business.OrderQueue.OrderRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.delivery.ViewDeliveriesJPanel;

/**
 *
 * @author Luciela us Biktria
 */
public final class AssignRiderJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final RiderDirectory riderDirectory;
    private final EcoSystem system;
    private final DeliveryDirectory deliveryDirectory;
    
    private final JCheckBox[] regionCheckBoxes;

    /**
     * Creates new form AssignRiderJPanel
     * @param userProcessContainer
     * @param system
     * @param riderDirectory
     * @param orderToEdit
     * @param deliveryDirectory
     */
    public AssignRiderJPanel(JPanel userProcessContainer, EcoSystem system, RiderDirectory riderDirectory, DeliveryDirectory deliveryDirectory, CoffeeOrderRequest orderToEdit) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.riderDirectory = riderDirectory;
        this.deliveryDirectory = deliveryDirectory;
        
        regionCheckBoxes = new JCheckBox[] {
            chkRiderRegion1, chkRiderRegion2, chkRiderRegion3, chkRiderRegion4, 
            chkRiderRegion5, chkRiderRegion6, chkRiderRegion7, chkRiderRegion8, 
            chkRiderRegion9, chkRiderRegion10
        };
        
        populateComboBoxes();
        
        if (orderToEdit != null) {
            cbxOrderID.setSelectedItem(orderToEdit);
            cbxOrderIDActionPerformed(null);
        } else if (cbxOrderID.getItemCount() > 0) {
            cbxOrderID.setSelectedIndex(0);
            cbxOrderIDActionPerformed(null);
        }
    }
    
    private ArrayList<CoffeeOrderRequest> getAllCoffeeOrders() {
        ArrayList<CoffeeOrderRequest> list = new ArrayList<>();
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof CoffeeChainEnterprise) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof CafeOperationOrganization) {
                            for (OrderRequest req : org.getWorkQueue().getWorkRequestList()) {
                                if (req instanceof CoffeeOrderRequest coffeeOrderRequest) {
                                    list.add(coffeeOrderRequest);
                                }
                            }
                        }
                    }
                }
            }
        }
        return list;
    }
    
    public void populateComboBoxes() {
        cbxOrderID.removeAllItems();
        cbxRiderID.removeAllItems();
        
        for (CoffeeOrderRequest req : getAllCoffeeOrders()) {
            if ("Delivery".equalsIgnoreCase(req.getOrderType())) {
                cbxOrderID.addItem(req);
            }
        }
        
        for (Rider r : riderDirectory.getEmployeeList()) {
            cbxRiderID.addItem(r);
        }
    }
    
    private void setRiderCheckboxes(int[] regions) {
        for (JCheckBox chk : regionCheckBoxes) {
            chk.setSelected(false);
        }
        if (regions == null) return;

        for (int regionNum : regions) {
            if (regionNum >= 1 && regionNum <= 10) {
                regionCheckBoxes[regionNum - 1].setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        lblOrderID = new javax.swing.JLabel();
        lblOrderContents = new javax.swing.JLabel();
        lblOrderDestination = new javax.swing.JLabel();
        lblOrderRegion = new javax.swing.JLabel();
        lblOrderStatus = new javax.swing.JLabel();
        txtOrderContents = new javax.swing.JTextField();
        txtOrderDestination = new javax.swing.JTextField();
        txtOrderRegion = new javax.swing.JTextField();
        txtOrderStatus = new javax.swing.JTextField();
        lblRiderID = new javax.swing.JLabel();
        lblRiderName = new javax.swing.JLabel();
        lblRiderPhone = new javax.swing.JLabel();
        lblRiderRegions = new javax.swing.JLabel();
        txtRiderName = new javax.swing.JTextField();
        txtRiderPhone = new javax.swing.JTextField();
        cbxRiderID = new javax.swing.JComboBox();
        cbxOrderID = new javax.swing.JComboBox();
        chkRiderRegion1 = new javax.swing.JCheckBox();
        chkRiderRegion2 = new javax.swing.JCheckBox();
        chkRiderRegion3 = new javax.swing.JCheckBox();
        chkRiderRegion4 = new javax.swing.JCheckBox();
        chkRiderRegion5 = new javax.swing.JCheckBox();
        chkRiderRegion6 = new javax.swing.JCheckBox();
        chkRiderRegion7 = new javax.swing.JCheckBox();
        chkRiderRegion8 = new javax.swing.JCheckBox();
        chkRiderRegion9 = new javax.swing.JCheckBox();
        chkRiderRegion10 = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Delivery Assignment");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnEdit.setText("Assign Delivery Rider");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 210, -1));

        btnConfirm.setText("Confirm and Request Delivery");
        btnConfirm.setEnabled(false); // Initially disabled until user clicks 'Assign Rider'
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 210, -1));

        lblOrderID.setText("Order (ID)");
        add(lblOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        lblOrderContents.setText("Contents");
        add(lblOrderContents, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        lblOrderDestination.setText("Destination");
        add(lblOrderDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblOrderRegion.setText("Region");
        add(lblOrderRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        lblOrderStatus.setText("Status");
        add(lblOrderStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        txtOrderContents.setEnabled(false);
        add(txtOrderContents, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 250, -1));

        txtOrderDestination.setEnabled(false);
        add(txtOrderDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, -1));

        txtOrderRegion.setEnabled(false);
        add(txtOrderRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 250, -1));

        txtOrderStatus.setEnabled(false);
        add(txtOrderStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 250, -1));

        lblRiderID.setText("Rider (ID)");
        add(lblRiderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        lblRiderName.setText("Rider Name");
        add(lblRiderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        lblRiderPhone.setText("Rider Phone Number");
        add(lblRiderPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        lblRiderRegions.setText("Rider Regions");
        add(lblRiderRegions, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        txtRiderName.setEnabled(false);
        add(txtRiderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 250, -1));

        txtRiderPhone.setEnabled(false);
        add(txtRiderPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 250, -1));

        cbxRiderID.setEnabled(false);
        cbxRiderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRiderIDActionPerformed(evt);
            }
        });
        add(cbxRiderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 250, -1));

        cbxOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOrderIDActionPerformed(evt);
            }
        });
        add(cbxOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 250, -1));

        chkRiderRegion1.setText("Region 1");
        chkRiderRegion1.setEnabled(false);
        add(chkRiderRegion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        chkRiderRegion2.setText("Region 2");
        chkRiderRegion2.setEnabled(false);
        add(chkRiderRegion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        chkRiderRegion3.setText("Region 3");
        chkRiderRegion3.setEnabled(false);
        add(chkRiderRegion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        chkRiderRegion4.setText("Region 4");
        chkRiderRegion4.setEnabled(false);
        add(chkRiderRegion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        chkRiderRegion5.setText("Region 5");
        chkRiderRegion5.setEnabled(false);
        add(chkRiderRegion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        chkRiderRegion6.setText("Region 6");
        chkRiderRegion6.setEnabled(false);
        add(chkRiderRegion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        chkRiderRegion7.setText("Region 7");
        chkRiderRegion7.setEnabled(false);
        add(chkRiderRegion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        chkRiderRegion8.setText("Region 8");
        chkRiderRegion8.setEnabled(false);
        add(chkRiderRegion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        chkRiderRegion9.setText("Region 9");
        chkRiderRegion9.setEnabled(false);
        add(chkRiderRegion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        chkRiderRegion10.setText("Region 10");
        chkRiderRegion10.setEnabled(false);
        add(chkRiderRegion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        if (btnEdit.getText().equals("Assign Delivery Rider")) {
            CoffeeOrderRequest selectedOrder = (CoffeeOrderRequest) cbxOrderID.getSelectedItem();
            if (selectedOrder == null) {
                JOptionPane.showMessageDialog(this, "No order selected.");
                return;
            }
            if (selectedOrder.getDestination() == null) {
                JOptionPane.showMessageDialog(this, "Order has no valid destination. Please go to Manage Destinations first.");
                return;
            }
            
            cbxOrderID.setEnabled(false);
            cbxRiderID.setEnabled(true);
            btnEdit.setText("Cancel Selection");
            btnConfirm.setEnabled(true);
            
        } else {
            cbxOrderID.setEnabled(true);
            cbxRiderID.setEnabled(false);
            btnEdit.setText("Assign Delivery Rider");
            btnConfirm.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        CoffeeOrderRequest selectedOrder = (CoffeeOrderRequest) cbxOrderID.getSelectedItem();
        Rider selectedRider = (Rider) cbxRiderID.getSelectedItem();
        
        if (selectedOrder == null || selectedRider == null) {
            JOptionPane.showMessageDialog(this, "Please select both an order and a rider.");
            return;
        }
        
        try {
            Delivery d = new Delivery(selectedOrder, selectedRider);
            deliveryDirectory.addDelivery(d);
            
            selectedOrder.setStatus("Assigned");
            
            JOptionPane.showMessageDialog(this, "Rider assigned successfully! Order status updated to 'Assigned'.");

            cbxOrderID.setEnabled(true);
            cbxRiderID.setEnabled(false);
            btnEdit.setText("Assign Delivery Rider");
            btnConfirm.setEnabled(false);
            
            cbxOrderIDActionPerformed(null);
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Assignment Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        if (componentArray.length > 0) {
            Component component = componentArray[componentArray.length - 1];
            if (component instanceof ViewDeliveriesJPanel viewPanel) {
                viewPanel.populateTable();
            }
        }
        CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbxRiderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRiderIDActionPerformed
        Rider r = (Rider) cbxRiderID.getSelectedItem();
        if (r != null) {
            txtRiderName.setText(r.getFirstName() + " " + r.getLastName());
            txtRiderPhone.setText(String.valueOf(r.getPhoneNumber()));
            setRiderCheckboxes(r.getRegions());
        } else {
            txtRiderName.setText("");
            txtRiderPhone.setText("");
            setRiderCheckboxes(null);
        }
    }//GEN-LAST:event_cbxRiderIDActionPerformed

    private void cbxOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOrderIDActionPerformed
        CoffeeOrderRequest order = (CoffeeOrderRequest) cbxOrderID.getSelectedItem();
        if (order != null) {
            txtOrderContents.setText(order.getMessage());
            txtOrderStatus.setText(order.getStatus());
            
            if (order.getDestination() != null) {
                txtOrderDestination.setText(order.getDestination().getAddress());
                txtOrderRegion.setText(String.valueOf(order.getDestination().getRegion()));
            } else {
                txtOrderDestination.setText("N/A - Set in Manage Destinations");
                txtOrderRegion.setText("N/A");
            }
            
            Delivery existing = deliveryDirectory.findDeliveryByOrder(order);
            if (existing != null) {
                cbxRiderID.setSelectedItem(existing.getRider());
                cbxRiderIDActionPerformed(null);
            } else {
                if (cbxRiderID.getItemCount() > 0) cbxRiderID.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_cbxOrderIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox cbxOrderID;
    private javax.swing.JComboBox cbxRiderID;
    private javax.swing.JCheckBox chkRiderRegion1;
    private javax.swing.JCheckBox chkRiderRegion10;
    private javax.swing.JCheckBox chkRiderRegion2;
    private javax.swing.JCheckBox chkRiderRegion3;
    private javax.swing.JCheckBox chkRiderRegion4;
    private javax.swing.JCheckBox chkRiderRegion5;
    private javax.swing.JCheckBox chkRiderRegion6;
    private javax.swing.JCheckBox chkRiderRegion7;
    private javax.swing.JCheckBox chkRiderRegion8;
    private javax.swing.JCheckBox chkRiderRegion9;
    private javax.swing.JLabel lblOrderContents;
    private javax.swing.JLabel lblOrderDestination;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderRegion;
    private javax.swing.JLabel lblOrderStatus;
    private javax.swing.JLabel lblRiderID;
    private javax.swing.JLabel lblRiderName;
    private javax.swing.JLabel lblRiderPhone;
    private javax.swing.JLabel lblRiderRegions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtOrderContents;
    private javax.swing.JTextField txtOrderDestination;
    private javax.swing.JTextField txtOrderRegion;
    private javax.swing.JTextField txtOrderStatus;
    private javax.swing.JTextField txtRiderName;
    private javax.swing.JTextField txtRiderPhone;
    // End of variables declaration//GEN-END:variables
}