/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeliveryRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DeliveryDispatcherOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Luciela us Biktria
 */
public class DeliveryDispatcherWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final DeliveryDispatcherOrganization organization;
    private final Enterprise enterprise;
    private final UserAccount userAccount;

    /**
     * Creates new form DeliveryDispatcherWorkArea
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param business
     * @param enterprise
     */
    public DeliveryDispatcherWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DeliveryDispatcherOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageDeliveries = new javax.swing.JButton();
        btnManageDestinations = new javax.swing.JButton();
        btnManageRiders = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Delivery Dispatch Control Panel");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        btnManageDeliveries.setText("Manage Deliveries");
        btnManageDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliveriesActionPerformed(evt);
            }
        });
        add(btnManageDeliveries, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 230, -1));

        btnManageDestinations.setText("Manage Delivery Destinations");
        btnManageDestinations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDestinationsActionPerformed(evt);
            }
        });
        add(btnManageDestinations, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 230, -1));

        btnManageRiders.setText("Manage Riders");
        btnManageRiders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRidersActionPerformed(evt);
            }
        });
        add(btnManageRiders, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliveriesActionPerformed
        ViewDeliveriesJPanel panel = new ViewDeliveriesJPanel(userProcessContainer, organization.getWorkQueue(), organization.getRiderDirectory(), organization.getDeliveryDirectory());
        userProcessContainer.add("ViewDeliveriesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeliveriesActionPerformed

    private void btnManageDestinationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDestinationsActionPerformed
        ManageDestinationsJPanel panel = new ManageDestinationsJPanel(
                userProcessContainer, 
                organization.getWorkQueue(), 
                organization.getDeliveryDirectory(), 
                organization.getDestinationDirectory()
        );
        userProcessContainer.add("ManageDestinationsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDestinationsActionPerformed

    private void btnManageRidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRidersActionPerformed
        // Pass the entire organization so the panel can access EmployeeDirectory and UserAccountDirectory
        ManageRiderJPanel panel = new ManageRiderJPanel(userProcessContainer, organization);
        userProcessContainer.add("ManageRiderJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRidersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDeliveries;
    private javax.swing.JButton btnManageDestinations;
    private javax.swing.JButton btnManageRiders;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}