/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeliveryRole;

/**
 *
 * @author Luciela us Biktria
 */
public class ManageRiderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRiderJPanel
     */
    public ManageRiderJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiders = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnNewCancel = new javax.swing.JButton();
        btnEditSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblRiderID = new javax.swing.JLabel();
        lblRiderPhoneNum = new javax.swing.JLabel();
        lblRiderFirstName = new javax.swing.JLabel();
        lblRiderLastName = new javax.swing.JLabel();
        txtAccountUsername = new javax.swing.JLabel();
        lblAccountPassword = new javax.swing.JLabel();
        lblRiderRegions = new javax.swing.JLabel();
        chkRiderRegion1 = new javax.swing.JCheckBox();
        chkRiderRegion2 = new javax.swing.JCheckBox();
        chkRiderRegion3 = new javax.swing.JCheckBox();
        chkRiderRegion4 = new javax.swing.JCheckBox();
        chkRiderRegion5 = new javax.swing.JCheckBox();
        chkRiderRegion6 = new javax.swing.JCheckBox();
        chkRiderRegion7 = new javax.swing.JCheckBox();
        chkRiderRegion8 = new javax.swing.JCheckBox();
        chkRiderRegion9 = new javax.swing.JCheckBox();
        chkRiderRegion10 = new javax.swing.JCheckBox();
        txtRiderID = new javax.swing.JTextField();
        txtRiderPhoneNum = new javax.swing.JTextField();
        txtRiderFirstName = new javax.swing.JTextField();
        txtRiderLastName = new javax.swing.JTextField();
        txtAccountPassword = new javax.swing.JTextField();
        lblAccountUsername = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRiders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rider ID", "Rider Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRiders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 550));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        btnNewCancel.setText("New");
        btnNewCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCancelActionPerformed(evt);
            }
        });
        add(btnNewCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        btnEditSave.setText("Edit");
        btnEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaveActionPerformed(evt);
            }
        });
        add(btnEditSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        lblTitle.setText("Rider Management & Registration");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        lblRiderID.setText("Rider ID");
        add(lblRiderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        lblRiderPhoneNum.setText("Rider Phone Number");
        add(lblRiderPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        lblRiderFirstName.setText("Rider First Name");
        add(lblRiderFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        lblRiderLastName.setText("Rider Last Name");
        add(lblRiderLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        txtAccountUsername.setText("Account Username");
        add(txtAccountUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        lblAccountPassword.setText("Account Password");
        add(lblAccountPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        lblRiderRegions.setText("Rider Delivery Regions");
        add(lblRiderRegions, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        chkRiderRegion1.setText("Region 1");
        chkRiderRegion1.setEnabled(false);
        add(chkRiderRegion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        chkRiderRegion2.setText("Region 2");
        chkRiderRegion2.setEnabled(false);
        add(chkRiderRegion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        chkRiderRegion3.setText("Region 3");
        chkRiderRegion3.setEnabled(false);
        add(chkRiderRegion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        chkRiderRegion4.setText("Region 4");
        chkRiderRegion4.setEnabled(false);
        add(chkRiderRegion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        chkRiderRegion5.setText("Region 5");
        chkRiderRegion5.setEnabled(false);
        add(chkRiderRegion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        chkRiderRegion6.setText("Region 6");
        chkRiderRegion6.setEnabled(false);
        add(chkRiderRegion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        chkRiderRegion7.setText("Region 7");
        chkRiderRegion7.setEnabled(false);
        add(chkRiderRegion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        chkRiderRegion8.setText("Region 8");
        chkRiderRegion8.setEnabled(false);
        add(chkRiderRegion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        chkRiderRegion9.setText("Region 9");
        chkRiderRegion9.setEnabled(false);
        add(chkRiderRegion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        chkRiderRegion10.setText("Region 10");
        chkRiderRegion10.setEnabled(false);
        add(chkRiderRegion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        txtRiderID.setEnabled(false);
        add(txtRiderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 230, -1));

        txtRiderPhoneNum.setEnabled(false);
        add(txtRiderPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 230, -1));

        txtRiderFirstName.setEnabled(false);
        add(txtRiderFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 230, -1));

        txtRiderLastName.setEnabled(false);
        add(txtRiderLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, -1));

        txtAccountPassword.setEnabled(false);
        add(txtAccountPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 230, -1));

        lblAccountUsername.setEnabled(false);
        add(lblAccountUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewCancelActionPerformed

    private void btnEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditSave;
    private javax.swing.JButton btnNewCancel;
    private javax.swing.JCheckBox chkRiderRegion1;
    private javax.swing.JCheckBox chkRiderRegion10;
    private javax.swing.JCheckBox chkRiderRegion2;
    private javax.swing.JCheckBox chkRiderRegion3;
    private javax.swing.JCheckBox chkRiderRegion4;
    private javax.swing.JCheckBox chkRiderRegion5;
    private javax.swing.JCheckBox chkRiderRegion6;
    private javax.swing.JCheckBox chkRiderRegion7;
    private javax.swing.JCheckBox chkRiderRegion8;
    private javax.swing.JCheckBox chkRiderRegion9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountPassword;
    private javax.swing.JTextField lblAccountUsername;
    private javax.swing.JLabel lblRiderFirstName;
    private javax.swing.JLabel lblRiderID;
    private javax.swing.JLabel lblRiderLastName;
    private javax.swing.JLabel lblRiderPhoneNum;
    private javax.swing.JLabel lblRiderRegions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblRiders;
    private javax.swing.JTextField txtAccountPassword;
    private javax.swing.JLabel txtAccountUsername;
    private javax.swing.JTextField txtRiderFirstName;
    private javax.swing.JTextField txtRiderID;
    private javax.swing.JTextField txtRiderLastName;
    private javax.swing.JTextField txtRiderPhoneNum;
    // End of variables declaration//GEN-END:variables
}
