/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeliveryRole;

import Business.EcoSystem;
import Business.Enterprise.CoffeeChainEnterprise;
import Business.Enterprise.DeliveryDepartment.Delivery;
import Business.Enterprise.DeliveryDepartment.DeliveryDirectory;
import Business.Enterprise.DeliveryDepartment.RiderDirectory;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.OrderQueue.CoffeeOrderRequest;
import Business.OrderQueue.OrderRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.DeliveryRole.AssignRiderJPanel;
import Business.Organization.BeverageProductionOrganization;

/**
 *
 * @author Luciela us Biktria
 */
public final class ViewDeliveriesJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final EcoSystem system;
    private final RiderDirectory riderDirectory;
    private final DeliveryDirectory deliveryDirectory;

    /**
     * Creates new form ViewDeliveriesJPanel
     * @param userProcessContainer
     * @param system
     * @param riderDirectory
     * @param deliveryDirectory
     */
    public ViewDeliveriesJPanel(JPanel userProcessContainer, EcoSystem system, RiderDirectory riderDirectory, DeliveryDirectory deliveryDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.riderDirectory = riderDirectory;
        this.deliveryDirectory = deliveryDirectory;
        
        populateTable();
    }
    
    private ArrayList<CoffeeOrderRequest> getAllCoffeeOrders() {
        ArrayList<CoffeeOrderRequest> list = new ArrayList<>();
        // Iterate entire ecosystem to find CoffeeChain -> CafeOperation -> Orders
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof CoffeeChainEnterprise) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof BeverageProductionOrganization) {
                            for (OrderRequest req : org.getWorkQueue().getWorkRequestList()) {
                                if (req instanceof CoffeeOrderRequest) {
                                    list.add((CoffeeOrderRequest) req);
                                }
                            }
                        }
                    }
                }
            }
        }
        return list;
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrders.getModel();
        model.setRowCount(0);
        
        for (CoffeeOrderRequest order : getAllCoffeeOrders()) {
            
            if ("Delivery".equalsIgnoreCase(order.getOrderType())) {
                
                Delivery delivery = deliveryDirectory.findDeliveryByOrder(order);
                
                Object[] row = new Object[6];
                row[0] = order; 
                row[1] = order.getRequestDate();
                
                if (delivery != null) {
                    row[2] = delivery.getDateTimeArrived() == 0 ? "Pending" : delivery.getDateTimeArrived();
                    row[3] = delivery.getRider().getFirstName() + " " + delivery.getRider().getLastName();
                } else {
                    row[2] = "N/A";
                    row[3] = "Unassigned";
                }
                
                if (order.getDestination() != null) {
                    row[4] = order.getDestination().getAddress();
                } else {
                    row[4] = "Needs Location"; // Indicates Dispatcher needs to assign destination
                }
                
                row[5] = order.getStatus();
                
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAssignRider = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 110, -1));

        btnAssignRider.setText("Assign Rider");
        btnAssignRider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRiderActionPerformed(evt);
            }
        });
        add(btnAssignRider, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 110, -1));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date Ordered", "Date Delivered", "Assigned Rider", "Destination", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 117, 720, 370));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Manage Orders and Pending Deliveries");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignRiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRiderActionPerformed
        int selectedRow = tblOrders.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order from the list.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        CoffeeOrderRequest selectedOrder = (CoffeeOrderRequest) tblOrders.getValueAt(selectedRow, 0);
        String status = selectedOrder.getStatus();
        
        if ("Delivered".equalsIgnoreCase(status) || "In-Progress".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "This order is " + status + " and cannot be modified.", "Action Not Allowed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        AssignRiderJPanel panel = new AssignRiderJPanel(userProcessContainer, system, riderDirectory, deliveryDirectory, selectedOrder);
        userProcessContainer.add("AssignRiderJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignRiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRider;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}