/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeliveryRole;

import Business.Enterprise.DeliveryDepartment.Delivery;
import Business.Enterprise.DeliveryDepartment.DeliveryDirectory;
import Business.Enterprise.DeliveryDepartment.RiderDirectory;
import Business.OrderQueue.CoffeeOrderRequest;
import Business.OrderQueue.OrderQueue;
import Business.OrderQueue.OrderRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciela us Biktria
 */
public final class ViewDeliveriesJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final OrderQueue orderQueue;
    private final RiderDirectory riderDirectory;
    private final DeliveryDirectory deliveryDirectory;

    /**
     * Creates new form ViewDeliveriesJPanel
     * @param userProcessContainer
     * @param orderQueue
     * @param riderDirectory
     * @param deliveryDirectory
     */
    public ViewDeliveriesJPanel(JPanel userProcessContainer, OrderQueue orderQueue, RiderDirectory riderDirectory, DeliveryDirectory deliveryDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.orderQueue = orderQueue;
        this.riderDirectory = riderDirectory;
        this.deliveryDirectory = deliveryDirectory;
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrders.getModel();
        model.setRowCount(0);
        
        for (OrderRequest request : orderQueue.getWorkRequestList()) {
            if (request instanceof CoffeeOrderRequest) {
                CoffeeOrderRequest order = (CoffeeOrderRequest) request;
                
                Delivery delivery = deliveryDirectory.findDeliveryByOrder(order);
                
                Object[] row = new Object[6];
                row[0] = order; 
                row[1] = order.getRequestDate();
                
                if (delivery != null) {
                    row[2] = delivery.getDateTimeArrived() == 0 ? "Pending" : delivery.getDateTimeArrived();
                    row[3] = delivery.getRider().getFirstName() + " " + delivery.getRider().getLastName();
                } else {
                    row[2] = "N/A";
                    row[3] = "Unassigned";
                }
                
                if (order.getDestination() != null) {
                    row[4] = order.getDestination().getAddress();
                } else {
                    row[4] = "In-Store/None";
                }
                
                row[5] = order.getStatus();
                
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAssignRider = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 110, -1));

        btnAssignRider.setText("Assign Rider");
        btnAssignRider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRiderActionPerformed(evt);
            }
        });
        add(btnAssignRider, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 110, -1));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date Ordered", "Date Delivered", "Assigned Rider", "Destination", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 117, 720, 370));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Manage Orders and Pending Deliveries");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignRiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRiderActionPerformed
        int selectedRow = tblOrders.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order from the list.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        CoffeeOrderRequest selectedOrder = (CoffeeOrderRequest) tblOrders.getValueAt(selectedRow, 0);
        
        if ("Delivered".equalsIgnoreCase(selectedOrder.getStatus())) {
            JOptionPane.showMessageDialog(this, "This order has already been delivered and cannot be modified.", "Action Not Allowed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        AssignRiderJPanel panel = new AssignRiderJPanel(userProcessContainer, orderQueue, riderDirectory, deliveryDirectory, selectedOrder);
        userProcessContainer.add("AssignRiderJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignRiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRider;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}